### ISSUE TITLE
Broken with the latest VTOL Mod-Loader update (which moved it to steam).

### ISSUE THREAD

**Issue by MarshMello0** [McFredward/vtol_bhaptics#1]
Hey I just wanted to let you know that the VTOL VR Mod Loader moved over to [steam](https://store.steampowered.com/app/3018410/VTOL_VR_Mod_Loader/) and sadly there is no backwards compabitity.

I saw someone on the steam workshop wanted this mod and attempted to reupload the website version as hidden on the steam workshop, but that sadly doesn't work.

The only code changes I think you would need to make (except fixing bugs from game updates) is updating the entry point and Harmony patches. I'm happy to help you in the discord or here if you want to update the mod. 

Feel free to close this issue. It was just my way of reaching out to you

**Comment by McFredward** [comment]
> Hey I just wanted to let you know that the VTOL VR Mod Loader moved over to [steam](https://store.steampowered.com/app/3018410/VTOL_VR_Mod_Loader/) and sadly there is no backwards compabitity.
> 
> I saw someone on the steam workshop wanted this mod and attempted to reupload the website version as hidden on the steam workshop, but that sadly doesn't work.
> 
> The only code changes I think you would need to make (except fixing bugs from game updates) is updating the entry point and Harmony patches. I'm happy to help you in the discord or here if you want to update the mod.
> 
> Feel free to close this issue. It was just my way of reaching out to you

Hi! Thanks for reaching me out.
Will look into it the next days. Probably this or next weekend.
Do you have some code samples of a mod which uses the new mod-loader on Steam?

**Comment by MarshMello0** [comment]
> Do you have some code samples of a mod which uses the new mod-loader on Steam?

I have a few small ones:
- [S-CAM F12](https://gitlab.com/ben-w/s-cam-f12)
- [Helmet Pop](https://gitlab.com/ben-w/helmet-pop)
- [Music Shuffle](https://gitlab.com/ben-w/music-shuffle)
- [Media Controls](https://gitlab.com/ben-w/media-controls)


I would say the music shuffle is a good example of the entry point and harmony. 

With a quick skim over, the class you inherit has changed from VTOLMOD to VtolMod

https://github.com/McFredward/vtol_bhaptics/blob/9d819a601faab82312385389158ef78c60c31ad7/vtol_bhaptics/Main.cs#L15

https://gitlab.com/ben-w/music-shuffle/-/blob/main/Music%20Shuffle/Main.cs?ref_type=heads#L9

You don't need to do this harmony patch anymore, the mod loader does it for you (As we now support unloading)
https://github.com/McFredward/vtol_bhaptics/blob/9d819a601faab82312385389158ef78c60c31ad7/vtol_bhaptics/Main.cs#L18

ModLoaded isn't a thing anymore, you can just use [Unity's Awake](https://docs.unity3d.com/ScriptReference/MonoBehaviour.Awake.html)
https://github.com/McFredward/vtol_bhaptics/blob/9d819a601faab82312385389158ef78c60c31ad7/vtol_bhaptics/Main.cs#L25

VTOLAPI got removed from the mod loader (to make the code base simpler), it is now a [seperate mod](https://steamcommunity.com/sharedfiles/filedetails/?id=3265689427) you can have a depedency on. Have a read through its description to find where steam downloads it to

https://github.com/McFredward/vtol_bhaptics/blob/9d819a601faab82312385389158ef78c60c31ad7/vtol_bhaptics/Main.cs#L27

We've upgraded to [HarmonyX](https://github.com/BepInEx/HarmonyX), you can either pull it from NuGet or reference it from the `@ModLoader\Managed` folder. You'll have to change this like to I think HarmonyLib

https://github.com/McFredward/vtol_bhaptics/blob/9d819a601faab82312385389158ef78c60c31ad7/vtol_bhaptics/Main.cs#L8


For general guides, we have a [getting stared here](https://docs.vtolvr-mods.com/creating-a-mod/first-mod/setup.html). I have updated the "Your first mod" but don't follow the "Advancing" page as I haven't gotten around to updating that section yet. The point which I would recomend is try using Danku's template and then copy your classes over. It isn't git friendly, but it has some automations when building and referencing game files for you.
